# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import users.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='InoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=130, unique=True, verbose_name='username')),
                ('user_type', models.CharField(choices=[(None, 'type'), ('Owner', 'Owner'), ('Employee', 'Employee')], max_length=10)),
                ('name', models.CharField(max_length=130, verbose_name='full name')),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('username',),
                'verbose_name': 'Ino User',
                'verbose_name_plural': 'Ino Users',
            },
            managers=[
                ('objects', users.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InoDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=130, verbose_name='full name')),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('driving_licence', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Ino Driver',
                'verbose_name_plural': 'Ino Drivers',
            },
        ),
    ]
