# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bus_number',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
