# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0003_auto_20170703_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='busparameter',
            name='battery',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
