# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0004_busparameter_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='running_status',
            field=models.BooleanField(default=False),
        ),
    ]
